/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fis.poo.cartelera;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author usuario
 */
public class GuiCartelera extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiCartelera.class.getName());

    
    ArrayList<Pelicula> peliculas = new ArrayList<>();
    
    private Cine cine;
    /**
     * Creates new form GuiCartelera
     */
    public GuiCartelera() {
    this(new Cine());
}
    
    public GuiCartelera(Cine cine) {
        initComponents();
        this.cine = cine;
        
        this.setLocationRelativeTo(null);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        lblLogo.setPreferredSize(new Dimension(100, 75));
        
        cbxUbicacion.addItem("Condado");
        cbxUbicacion.addItem("Quicentro");
        cbxUbicacion.addItem("CCI");
        
         peliculas.add(new Pelicula("Agua","Refrescante","/imagenes/Agua.jpeg","2h 40min"));
         peliculas.add(new Pelicula("SPIDER MAN UN NUEVO DIA","Tras el Día del Juicio Final, Peter"
                 + " Parker intenta centrarse en la universidad y abandonar a Spider-Man. "
                 + "Cuando una nueva amenaza pone en peligro a sus amigos, debe romper "
                 + "su promesa y volver al traje.","/imagenes/Spider.jpg","2h 40min")); 
         peliculas.add(new Pelicula("Agua","Refrescante","/imagenes/Agua.jpeg","2h 40min"));
         peliculas.add(new Pelicula("Spider","Accion","/imagenes/Spider.jpg","2h 40min"));
         peliculas.add(new Pelicula("Agua","Refrescante","/imagenes/Agua.jpeg","2h 40min"));
         peliculas.add(new Pelicula("Spider","Accion","/imagenes/Spider.jpg","2h 40min"));
         peliculas.add(new Pelicula("Agua","Refrescante","/imagenes/Agua.jpeg","2h 40min"));
         peliculas.add(new Pelicula("Spider","Accion","/imagenes/Spider.jpg","2h 40min"));
         peliculas.add(new Pelicula("Agua","Refrescante","/imagenes/Agua.jpeg","2h 40min"));
         peliculas.add(new Pelicula("Spider","Accion","/imagenes/Spider.jpg","2h 40min"));
         
         
         Collections.shuffle(peliculas);
         

        //colocarImagen(lblMovie1, peliculas.get(0).getPortada());
        
        
         JLabel[] labels = {lblMovie1, lblMovie2, lblMovie3, lblMovie4,
             lblMovie5,lblMovie6,lblMovie7,lblMovie8,lblMovie9,lblMovie10};

        for (int i = 0; i < labels.length; i++) {
            colocarImagen(labels[i], peliculas.get(i).getPortada());
        }
        
    }

     private void colocarImagen(javax.swing.JLabel label, ImageIcon icono) {

        Image imagen = icono.getImage().getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH);

        label.setIcon(new ImageIcon(imagen));
    }
    private void abrirPelicula(int index) {
        Pelicula p = peliculas.get(index);
        if (cbxUbicacion.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Seleccione una ubicación");
            return;
        }
        cine.setUbicacion(cbxUbicacion.getSelectedItem().toString());
        
        new VentanaPelicula(p,cine).setVisible(true);
        this.dispose();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        cbxUbicacion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblMovie1 = new javax.swing.JLabel();
        lblMovie2 = new javax.swing.JLabel();
        lblMovie3 = new javax.swing.JLabel();
        lblMovie4 = new javax.swing.JLabel();
        lblMovie5 = new javax.swing.JLabel();
        lblMovie6 = new javax.swing.JLabel();
        lblMovie7 = new javax.swing.JLabel();
        lblMovie9 = new javax.swing.JLabel();
        lblMovie8 = new javax.swing.JLabel();
        lblMovie10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N
        lblLogo.setMaximumSize(new java.awt.Dimension(100, 100));

        cbxUbicacion.addActionListener(this::cbxUbicacionActionPerformed);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Facturas");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setHorizontalScrollBar(null);

        lblMovie1.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie1.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie1.setOpaque(true);
        lblMovie1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie1MouseClicked(evt);
            }
        });

        lblMovie2.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie2.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie2.setOpaque(true);
        lblMovie2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie2MouseClicked(evt);
            }
        });

        lblMovie3.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie3.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie3.setOpaque(true);
        lblMovie3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie3MouseClicked(evt);
            }
        });

        lblMovie4.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie4.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie4.setOpaque(true);
        lblMovie4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie4MouseClicked(evt);
            }
        });

        lblMovie5.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie5.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie5.setOpaque(true);
        lblMovie5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie5MouseClicked(evt);
            }
        });

        lblMovie6.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie6.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie6.setOpaque(true);
        lblMovie6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie6MouseClicked(evt);
            }
        });

        lblMovie7.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie7.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie7.setOpaque(true);
        lblMovie7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie7MouseClicked(evt);
            }
        });

        lblMovie9.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie9.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie9.setOpaque(true);
        lblMovie9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie9MouseClicked(evt);
            }
        });

        lblMovie8.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie8.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie8.setOpaque(true);
        lblMovie8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie8MouseClicked(evt);
            }
        });

        lblMovie10.setBackground(new java.awt.Color(255, 255, 255));
        lblMovie10.setBorder(new javax.swing.border.MatteBorder(null));
        lblMovie10.setOpaque(true);
        lblMovie10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovie10MouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMovie9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMovie2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lblMovie5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMovie6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMovie8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovie3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMovie10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovie4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMovie7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMovie2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovie3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovie4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovie5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMovie6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovie7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovie9, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovie8, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovie10, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMovie1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie1MouseClicked
        abrirPelicula(0);
        /*Pelicula p = peliculas.get(0);
         new VentanaPelicula(p).setVisible(true);
         this.dispose();
         */
    }//GEN-LAST:event_lblMovie1MouseClicked

    private void lblMovie2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie2MouseClicked
        abrirPelicula(1); 
    }//GEN-LAST:event_lblMovie2MouseClicked

    private void lblMovie5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie5MouseClicked
        abrirPelicula(4);
    }//GEN-LAST:event_lblMovie5MouseClicked

    private void lblMovie3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie3MouseClicked
        abrirPelicula(2);
    }//GEN-LAST:event_lblMovie3MouseClicked

    private void lblMovie4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie4MouseClicked
        abrirPelicula(3);
    }//GEN-LAST:event_lblMovie4MouseClicked

    private void lblMovie9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie9MouseClicked
         abrirPelicula(8);
    }//GEN-LAST:event_lblMovie9MouseClicked

    private void lblMovie8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie8MouseClicked
         abrirPelicula(7);
    }//GEN-LAST:event_lblMovie8MouseClicked

    private void lblMovie10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie10MouseClicked
         abrirPelicula(9);
    }//GEN-LAST:event_lblMovie10MouseClicked

    private void lblMovie6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie6MouseClicked
        abrirPelicula(5);
    }//GEN-LAST:event_lblMovie6MouseClicked

    private void lblMovie7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovie7MouseClicked
        abrirPelicula(6);
    }//GEN-LAST:event_lblMovie7MouseClicked

    private void cbxUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUbicacionActionPerformed
   
        
        cbxUbicacion.addActionListener(e -> {
         if (cbxUbicacion.getSelectedIndex() != -1) {
          this.dispose();
         new GuiCartelera(cine).setVisible(true);
        }
    });
        
    }//GEN-LAST:event_cbxUbicacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        new Factura(cine).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuiCartelera().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxUbicacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMovie1;
    private javax.swing.JLabel lblMovie10;
    private javax.swing.JLabel lblMovie2;
    private javax.swing.JLabel lblMovie3;
    private javax.swing.JLabel lblMovie4;
    private javax.swing.JLabel lblMovie5;
    private javax.swing.JLabel lblMovie6;
    private javax.swing.JLabel lblMovie7;
    private javax.swing.JLabel lblMovie8;
    private javax.swing.JLabel lblMovie9;
    // End of variables declaration//GEN-END:variables
}
