/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fis.poo.cartelera;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author usuario
 */
public class VentanaBoletos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaBoletos.class.getName());
    
    private Funcion funcion;
    private Cine cine;
    
    
    public VentanaBoletos(Funcion funcion, Cine cine) {
        initComponents();
        this.funcion = funcion;
        this.cine=cine;
        this.setLocationRelativeTo(null);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnContinuar.setContentAreaFilled(false);
        btnContinuar.setFocusPainted(false);
        
        spGeneral.setModel(new SpinnerNumberModel(0, 0, 10, 1));
        spNino.setModel(new SpinnerNumberModel(0, 0, 10, 1));
        spMayor.setModel(new SpinnerNumberModel(0, 0, 10, 1) );
        
        actualizarTotal();
        
        colocarImagen(lblImagen, funcion.getPelicula().getPortada());
        lblTitulo.setText(funcion.getPelicula().getNombre());
        
        
    System.out.println("===== DATOS DE LA FUNCION =====");
    System.out.println("Pelicula: " + funcion.getPelicula().getNombre());
    System.out.println("Dia: " + funcion.getDia());
    System.out.println("Hora: " + funcion.getHora());
    System.out.println("Descripcion: " + funcion.getPelicula().getDescripcion());    
    System.out.println("===============================");    
        
    }
    
    public VentanaBoletos() {
        initComponents();
     
    }
    
    private void actualizarTotal() {

        int general = (Integer) spGeneral.getValue();
        int ninos = (Integer) spNino.getValue();
        int mayor =(Integer)spMayor.getValue();

        double total = general * 5.50 + ninos * 3.50+mayor*2.25;
        
        txtGeneral.setText("["+spGeneral.getValue()+"]"+"  Cliente General ");
        txtNino.setText("["+spNino.getValue()+"]"+"  Niños ");
        txtMayor.setText("["+spMayor.getValue()+"]"+"  3Ra Edad ");
   
        lblTotal.setText("  "+"$ " + total);
        
    }
    private void colocarImagen(javax.swing.JLabel label, ImageIcon icono) {

        Image imagen = icono.getImage().getScaledInstance(
            label.getWidth(),
            label.getHeight(),
            Image.SCALE_SMOOTH);

        label.setIcon(new ImageIcon(imagen));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt1 = new javax.swing.JTextArea();
        spGeneral = new javax.swing.JSpinner();
        txt2 = new javax.swing.JTextArea();
        spNino = new javax.swing.JSpinner();
        txt3 = new javax.swing.JTextArea();
        spMayor = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtGeneral = new javax.swing.JTextArea();
        txtNino = new javax.swing.JTextArea();
        txtMayor = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtP3 = new javax.swing.JTextArea();
        txtP1 = new javax.swing.JTextArea();
        txtP2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de Boletos");
        setPreferredSize(new java.awt.Dimension(1071, 714));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblImagen.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen.setBorder(new javax.swing.border.MatteBorder(null));
        lblImagen.setOpaque(true);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("← Selecciona Tus Voletos");
        btnBack.setBorder(new javax.swing.border.MatteBorder(null));
        btnBack.addActionListener(this::btnBackActionPerformed);

        txt1.setEditable(false);
        txt1.setBackground(new java.awt.Color(255, 255, 255));
        txt1.setColumns(20);
        txt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt1.setRows(5);
        txt1.setText("Cliente General \n$5.50\n");
        txt1.setAutoscrolls(false);
        txt1.setBorder(null);
        txt1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt1.setEnabled(false);
        txt1.setOpaque(false);

        spGeneral.setBorder(new javax.swing.border.MatteBorder(null));
        spGeneral.addChangeListener(this::spGeneralStateChanged);

        txt2.setEditable(false);
        txt2.setColumns(20);
        txt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt2.setRows(5);
        txt2.setText("Niños\n$3.50\n");
        txt2.setAutoscrolls(false);
        txt2.setBorder(null);
        txt2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt2.setEnabled(false);
        txt2.setOpaque(false);

        spNino.setBorder(new javax.swing.border.MatteBorder(null));
        spNino.addChangeListener(this::spNinoStateChanged);

        txt3.setEditable(false);
        txt3.setColumns(20);
        txt3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt3.setRows(5);
        txt3.setText("3Ra Edad\n$2.25\n");
        txt3.setAutoscrolls(false);
        txt3.setBorder(null);
        txt3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt3.setEnabled(false);
        txt3.setOpaque(false);

        spMayor.setBorder(new javax.swing.border.MatteBorder(null));
        spMayor.addChangeListener(this::spMayorStateChanged);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tipo de Boletos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spMayor)
                            .addComponent(spGeneral, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spNino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(spNino, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        btnContinuar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setBorder(new javax.swing.border.MatteBorder(null));
        btnContinuar.addActionListener(this::btnContinuarActionPerformed);

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtGeneral.setEditable(false);
        txtGeneral.setBackground(new java.awt.Color(255, 255, 255));
        txtGeneral.setColumns(20);
        txtGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGeneral.setRows(5);
        txtGeneral.setAutoscrolls(false);
        txtGeneral.setBorder(new javax.swing.border.MatteBorder(null));
        txtGeneral.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGeneral.setEnabled(false);

        txtNino.setEditable(false);
        txtNino.setBackground(new java.awt.Color(255, 255, 255));
        txtNino.setColumns(20);
        txtNino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNino.setRows(5);
        txtNino.setAutoscrolls(false);
        txtNino.setBorder(new javax.swing.border.MatteBorder(null));
        txtNino.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNino.setEnabled(false);
        txtNino.setVerifyInputWhenFocusTarget(false);

        txtMayor.setEditable(false);
        txtMayor.setBackground(new java.awt.Color(255, 255, 255));
        txtMayor.setColumns(20);
        txtMayor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMayor.setRows(5);
        txtMayor.setAutoscrolls(false);
        txtMayor.setBorder(new javax.swing.border.MatteBorder(null));
        txtMayor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMayor.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tus Boletos");

        txtP3.setEditable(false);
        txtP3.setBackground(new java.awt.Color(255, 255, 255));
        txtP3.setColumns(20);
        txtP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtP3.setRows(5);
        txtP3.setText("$3.50");
        txtP3.setAutoscrolls(false);
        txtP3.setBorder(null);
        txtP3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtP3.setEnabled(false);
        txtP3.setFocusable(false);
        txtP3.setOpaque(false);

        txtP1.setEditable(false);
        txtP1.setBackground(new java.awt.Color(255, 255, 255));
        txtP1.setColumns(20);
        txtP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtP1.setRows(5);
        txtP1.setText("$5.50");
        txtP1.setAutoscrolls(false);
        txtP1.setBorder(null);
        txtP1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtP1.setEnabled(false);
        txtP1.setFocusable(false);
        txtP1.setOpaque(false);

        txtP2.setEditable(false);
        txtP2.setBackground(new java.awt.Color(255, 255, 255));
        txtP2.setColumns(20);
        txtP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtP2.setRows(5);
        txtP2.setText("$2.25");
        txtP2.setAutoscrolls(false);
        txtP2.setBorder(null);
        txtP2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtP2.setEnabled(false);
        txtP2.setFocusable(false);
        txtP2.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtNino, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtMayor, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtP3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(txtNino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtP3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)))
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnBack)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(192, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      
        if (funcion.getAsientosFormateados().isEmpty()) {
            cine.eliminarFuncion(funcion);
        }
        new VentanaPelicula(funcion.getPelicula(),cine).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void spGeneralStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spGeneralStateChanged
        actualizarTotal();
    }//GEN-LAST:event_spGeneralStateChanged

    private void spNinoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spNinoStateChanged
        actualizarTotal();
    }//GEN-LAST:event_spNinoStateChanged

    private void spMayorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spMayorStateChanged
        actualizarTotal();
    }//GEN-LAST:event_spMayorStateChanged

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
    funcion.setBoletosGeneral((Integer) spGeneral.getValue());
    funcion.setBoletosNino((Integer) spNino.getValue());
    funcion.setBoletos3RaEdad((Integer)spMayor.getValue());

    new SeleccionAsientos(funcion,cine).setVisible(true);

    this.dispose();        
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaBoletos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spGeneral;
    private javax.swing.JSpinner spMayor;
    private javax.swing.JSpinner spNino;
    private javax.swing.JTextArea txt1;
    private javax.swing.JTextArea txt2;
    private javax.swing.JTextArea txt3;
    private javax.swing.JTextArea txtGeneral;
    private javax.swing.JTextArea txtMayor;
    private javax.swing.JTextArea txtNino;
    private javax.swing.JTextArea txtP1;
    private javax.swing.JTextArea txtP2;
    private javax.swing.JTextArea txtP3;
    // End of variables declaration//GEN-END:variables
}
